### ISSUE TITLE
"ResizeObserver loop" crash, React demo in mobile mode

### ISSUE THREAD

**Issue by brownieboy** [unblu/visitor-js-api-example#26] opened 2023-11-06 00:37 UTC
Run the React demo in mobile mode, i.e. browser width < 992px.   Clicking on the **New** drop-down button will crash the app with error:

> ResizeObserver loop completed with undelivered notifications.
>     at handleError (http://localhost:3000/static/js/bundle.js:42457:58)
>     at http://localhost:3000/static/js/bundle.js:42476:7

Full sized Desktop mode is fine.

Tested with latest Chrome browser on Windows 10.   On Firefox, I don't even need to click the button; the error triggers as soon as the browser window resizes.

**Comment by davideberlein** [comment] 2023-11-06 07:18
Thanks for the feedback @brownieboy, I'll have a look at it

**Comment by davideberlein** [comment] 2023-11-06 15:07
This isn't a real issue and is caused by the `webpack-dev-server` overlay feature.

This issue is caused by the `resize loop detection` of the `ResizeObserver` (see: https://github.com/juggle/resize-observer/blob/master/README.md#resize-loop-detection) for details.
All it does is fire an event on the `window` to indicate a warning. In our case we don't actually have a loop so it is not an error, however the `webpack-dev-server` used by React treats this as an error and displays it as such.

In theory the webpack devserver would allow to disable displaying this warning using the `overlay` config: https://webpack.js.org/configuration/dev-server/#overlay 
Unfortunately as far as I can see the `react scripts` we are using for this example don't allow us to change the specific settings for the overlay.

I have improved the code of the Unblu product to not trigger the `resize loop detection` anymore which will either be released with the current sprint (later this week) or the one after (week 2024.48).

Until then I think you just have to ignore the error ;-)

**Comment by davideberlein** [comment] 2023-11-20 08:39
@brownieboy the new version of the embedded component is now released and available on npmjs.
All reported issues are fixed with this and the latest version of the unblu product `7.38.2`

**Closed by davideberlein** 2023-11-20 08:39 UTC
